### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by LucSalommez** [nicolaspanel/TrainingSpeech#2]
Hello,

I really appreciate your efforts in order to gather an open voice dataset.
I had a question about licensing : 

The aeneas repo you linked in the README.md is under the AGPL v3 license which seems
to imply that your repo should be under the same license while the repo is under the MIT license.

My question is, if you have to switch this repo under AGPL v3, does it mean the voice dataset from the repo will be under AGPLv3 too ?

If that's the case, does it mean everyone using the dataset will have to be under AGPL too ?
Then I think it can be an issue for a lot of potential users of the repo.

I don't know if using training data under a license implies the same restriction as code though, but I thought it might be a good thing to ask you about this.

Thanks for your work,
Luc.

**Comment by nicolaspanel** [comment]
This repo is under MIT (source code)
It uses aenas internally but it do not imply that license have to be the same.

Contents (such as audiobooks recordings) have there own licenses (see `sources.json`) but they all enable reuse and redistribution.

**Comment by LucSalommez** [comment]
I interpreted AGPL as GPL and it seems like there is no propagation of license indeed.
Thanks for your answer :).

I am closing this issue.
