### ISSUE TITLE
Access denied on 2019-01-29_fr_FR.zip

### ISSUE THREAD

**Issue by romainsc** [nicolaspanel/TrainingSpeech#5]
Hi,

When I try to access the latest training data, I have an access denied from AWS: 

`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>D1F50C445BCCFF1B</RequestId><HostId>7jnxbLkym/zn/juZzH6wEe7NTbCErgReHGvqlFCsJbrgwA8eh7G8wR7BlLcPIV5EZs8wBDHdAOg=</HostId></Error>`

Best Regards,

**Comment by nicolaspanel** [comment]
the link was wrong, should be ok now
